/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFriendAction: typeof import('./src/components/AddFriendAction.vue')['default']
    FriendActions: typeof import('./src/components/FriendActions.vue')['default']
    FriendListItem: typeof import('./src/components/FriendListItem.vue')['default']
    MovieCard: typeof import('./src/components/MovieCard.vue')['default']
    MovieListItem: typeof import('./src/components/MovieListItem.vue')['default']
    ReceivedFriendRequestActions: typeof import('./src/components/ReceivedFriendRequestActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SentFriendRequestActions: typeof import('./src/components/SentFriendRequestActions.vue')['default']
    SwipedMoviesCard: typeof import('./src/components/SwipedMoviesCard.vue')['default']
    TabToggle: typeof import('./src/components/TabToggle.vue')['default']
    TabToogle: typeof import('./src/components/TabToogle.vue')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanEmpty: typeof import('vant/es')['Empty']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanRate: typeof import('vant/es')['Rate']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    ViewHeaderBar: typeof import('./src/components/ViewHeaderBar.vue')['default']
  }
}
